spring:
  #  数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #生存周期
      max-lifetime: 30000
      maxActive: 20
      # 配置获取连接等待超时的时间
      connectionTimeout: 30000
      #连接池中允许的最大连接数
      maximum-pool-size: 10
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://mysql.likexx.cn/weSource?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
  cache:
    type: redis

  redis:
    # Redis数据库索引（默认为0）
    daabase: 0
    # Redis服务器地址
    host: redis.likexx.cn
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
  # 连接超时时间（毫秒）
    timeout: 0
